language: go
go:
- stable
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/release.sh
  on:
    repo: sourceseed/seedr
    branch: master
    tags: true
env:
  global:
    secure: 3vV18lk1xrcQZ+Kk9LOx8eAOXIsC0VdXZ1z61RSiYG2hC23DGlcpSI7f3G/cAIbxj0RDZIn0QUncBmfL4+AXW2VFNXUC5fOheqiqr5bE1nLQTR35vMU1RkMaUAlpC9NAEl5gpWDwr8sQo4hENJW65oKT+YbaYOaf7R88HFo+lHGv12/xxCfinMTaGeKBfgRPJRlhEizG+Xpc3Tv/owVN89RuH77tBpPGhCALcY16qGpH5fvt+vTdttoNPZFl75tIvew+SxVl3D40XiVX3dxosn7A1848jf229rlSeC16No+93rnaMnr5XjRlC5FsVaK544ANCazI9r5f4a4LWAsh1YQlFay5obgTgWUf4aM0vzn3XR+uwgIbR6Z9CnvBH9q/sOiJ7UXds+AOiFpgVW0kWc9FvfDUhIlot0drMQTVv8UbhWhNuQu5HzvuHoZXpIYlU650yUUG6UvFdkolnYNJM+mev53JG+noEbMWhsEMk4Kd6B6PqwIkZGYvqaWrvspAQzHkow8VQPI/u+ZvwqE1/bMcGe6UzwwruE5RMqQPqVuHlrU0S5MRCIUU3pbYu1rPaZQSnEHLr8ofZ5OCb/7gD7odh0h/zLouF8IkmNZsg1f0UfRAw66LlV33gyWeMCSC6wyy4BhlczkSNF9hMkWGnIYMvLcU1Xc64w92JQo5aCE=
